version: 0.2

phases:
  install:
    commands:
      - yum install nodejs -y
      - yum install npm -y
      - npm install aws-cdk -g
      - pip install -r requirements.txt
     
  build:
    commands:
      - cdk bootstrap --template bootstrap-template.yaml
      - cdk deploy --require-approval never

artifacts:
  files: '**/*'
