version: 0.2

phases:
  install:
    commands:
      - yum install nodejs -y
      - yum install npm -y
      - npm install aws-cdk -g
      - pip install -r requirements.txt
     
  build:
    commands:
      - cdk ls
      - cdk synth


artifacts:
  files: '**/*'
